-- STUBSERVERAUDITLOGS_UAT (Oracle) — created only if missing (ignores ORA-00955).
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE ${schema}.STUBSERVERAUDITLOGS_UAT (
            ID            NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            USERNAME      VARCHAR2(100),
            SERVICE_NAME  VARCHAR2(255),
            ACTION_TYPE   VARCHAR2(50),
            "TIMESTAMP"   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
            REMARK        VARCHAR2(1000) DEFAULT '-',
            CONSTRAINT PK_STUBSERVERAUDITLOGS_UAT PRIMARY KEY (ID)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN   -- ORA-00955: name already used by an existing object
            RAISE;
        END IF;
END;
/
