-- STUBSERVER_MASTER_CATALOG_UAT (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBSERVER_MASTER_CATALOG_UAT', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBSERVER_MASTER_CATALOG_UAT (
        MASTERID            BIGINT NOT NULL,
        VSNAME              VARCHAR(150) NOT NULL,
        UPDATETIME          DATETIME NULL,
        STATUS              VARCHAR(50) NULL,
        BACKENDAPPLICATION  VARCHAR(300) NULL,
        BACKENDTYPE         VARCHAR(10) NULL,
        ENV_TYPE            VARCHAR(20) NULL,
        [GROUP]             VARCHAR(100) NULL,
        PORT                INT NULL,
        CONSTRAINT PK_STUBSERVER_MASTER_CATALOG_UAT PRIMARY KEY (MASTERID)
    );
END;
