-- STUBSERVERUSERS (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBSERVERUSERS', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBSERVERUSERS (
        ID          BIGINT IDENTITY(1,1) NOT NULL,
        USERNAME    VARCHAR(50)  NOT NULL,
        PASSWORD    VARCHAR(200) NOT NULL,
        EMAIL       VARCHAR(50)  NULL,
        FIRSTNAME   VARCHAR(50)  NULL,
        LASTNAME    VARCHAR(50)  NULL,
        USERROLE    VARCHAR(50)  NOT NULL,
        CREATED_BY  VARCHAR(50)  NOT NULL,
        CREATED_AT  DATETIME2    NULL
            CONSTRAINT DF_STUBSERVERUSERS_CREATED_AT DEFAULT SYSDATETIME(),
        UPDATED_BY  VARCHAR(50)  NULL,
        UPDATED_AT  DATETIME2    NULL
            CONSTRAINT DF_STUBSERVERUSERS_UPDATED_AT DEFAULT SYSDATETIME(),
        CONSTRAINT PK_STUBSERVERUSERS PRIMARY KEY (ID),
        CONSTRAINT UQ_STUBSERVERUSERS_USERNAME UNIQUE (USERNAME)
    );
END;
