-- AUTH_REFRESH_TOKENS (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.AUTH_REFRESH_TOKENS', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.AUTH_REFRESH_TOKENS (
        JTI         VARCHAR(64)  NOT NULL,
        USERNAME    VARCHAR(128) NOT NULL,
        EXPIRES_AT  DATETIME2    NOT NULL,
        REVOKED     CHAR(1)      NULL
            CONSTRAINT DF_AUTH_REFRESH_TOKENS_REVOKED DEFAULT 'N',
        ISSUED_AT   DATETIME2    NULL
            CONSTRAINT DF_AUTH_REFRESH_TOKENS_ISSUED_AT DEFAULT SYSDATETIME(),
        USER_AGENT  VARCHAR(512) NULL,
        IP          VARCHAR(64)  NULL,
        CONSTRAINT PK_AUTH_REFRESH_TOKENS PRIMARY KEY (JTI),
        CONSTRAINT CK_AUTH_REFRESH_TOKENS_REVOKED CHECK (REVOKED IN ('Y', 'N'))
    );
END;
