-- STUBSERVERAUDITLOGS_UAT (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBSERVERAUDITLOGS_UAT', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBSERVERAUDITLOGS_UAT (
        ID            BIGINT IDENTITY(1,1) NOT NULL,
        USERNAME      VARCHAR(100)  NULL,
        SERVICE_NAME  VARCHAR(255)  NULL,
        ACTION_TYPE   VARCHAR(50)   NULL,
        [TIMESTAMP]   DATETIME2     NULL
            CONSTRAINT DF_STUBSERVERAUDITLOGS_UAT_TIMESTAMP DEFAULT SYSDATETIME(),
        REMARK        VARCHAR(1000) NULL
            CONSTRAINT DF_STUBSERVERAUDITLOGS_UAT_REMARK DEFAULT '-',
        CONSTRAINT PK_STUBSERVERAUDITLOGS_UAT PRIMARY KEY (ID)
    );
END;
