-- STUBASSIGNEDSERVICES_QA (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBASSIGNEDSERVICES_QA', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBASSIGNEDSERVICES_QA (
        USERNAME    VARCHAR(255) NULL,
        SERVICENAME VARCHAR(255) NULL
    );
END;
