-- STUBASSIGNEDSERVICES_UAT (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBASSIGNEDSERVICES_UAT', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBASSIGNEDSERVICES_UAT (
        USERNAME    VARCHAR(255) NULL,
        SERVICENAME VARCHAR(255) NULL
    );
END;
