-- READYAPI_RESPONSE_TIME (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.READYAPI_RESPONSE_TIME', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.READYAPI_RESPONSE_TIME (
        RESPID       BIGINT    NOT NULL,
        METRICSID    BIGINT    NOT NULL,
        STARTTIME    DATETIME2 NOT NULL,
        ENDTIME      DATETIME2 NOT NULL,
        AVGRESPTIME  BIGINT    NULL,
        MAXRESPTIME  BIGINT    NULL,
        AVGTPS       BIGINT    NULL
    );
END;
