-- STUBSERVERQA_VSDETAILS (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.STUBSERVERQA_VSDETAILS', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.STUBSERVERQA_VSDETAILS (
        VSID                BIGINT NOT NULL,
        VSNAME              VARCHAR(255) NULL,
        PORT                INT NULL,
        LASTUPDATED         VARCHAR(30) NULL,
        USERNAME            VARCHAR(255) NULL,
        STATUS              VARCHAR(10) NULL,

        KEEPREQRESLOGS      VARCHAR(10) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_KEEPREQRESLOGS DEFAULT 'No',

        KEEPREQRESLOGSDAYS  VARCHAR(20) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_KEEPREQRESLOGSDAYS DEFAULT '15',

        SAVERESPTIME        VARCHAR(20) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_SAVERESPTIME DEFAULT 'No',

        [GROUP]             VARCHAR(100) NULL,
        TAGS                VARCHAR(100) NULL,

        DELAYMODE           VARCHAR(50) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_DELAYMODE DEFAULT 'FIXED',

        DELAY               BIGINT NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_DELAY DEFAULT 0,

        LOWERMS             BIGINT NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_LOWERMS DEFAULT 0,

        UPPERMS             BIGINT NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_UPPERMS DEFAULT 0,

        SIGMA               DECIMAL(10,4) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_SIGMA DEFAULT 0.0,

        MEDIANMS            DECIMAL(10,4) NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_MEDIANMS DEFAULT 0.0,

        TOTALTXN            INT NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_TOTALTXN DEFAULT 0,

        DELAYPERCENT        INT NULL
            CONSTRAINT DF_STUBSERVERQA_VSDETAILS_DELAYPERCENT DEFAULT 0,

        DATASOURCEENABLED   VARCHAR(10) NULL,

        CONSTRAINT PK_STUBSERVERQA_VSDETAILS PRIMARY KEY (VSID)
    );
END;
