-- VS_EXECUTIONMODE (SQL Server) — created only if missing.
IF OBJECT_ID('${schema}.VS_EXECUTIONMODE', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.VS_EXECUTIONMODE (
        VSID            BIGINT NOT NULL,
        MASTERID        VARCHAR(100) NOT NULL,
        VIRTSERVER      VARCHAR(50) NULL,
        EXECUTIONMODE   VARCHAR(50) NULL,
        UPDATETIME      DATETIME NULL,
        UPDATEDBY       VARCHAR(50) NULL,
        CONSTRAINT PK_VS_EXECUTIONMODE PRIMARY KEY (VSID)
    );
END;
